export enum RecoverRouteKey {
  FATAL = "FATAL",

  SETUP_CHOOSE_FRANCHISE = "SETUP_CHOOSE_FRANCHISE",
  STAFFING_BLOCKING = "STAFFING_BLOCKING",

  CAP_COMPLIANCE = "CAP_COMPLIANCE",
  ROSTER_CUTS = "ROSTER_CUTS",
  DEPTH_CHART = "DEPTH_CHART",

  DRAFT_SETUP = "DRAFT_SETUP",
  DRAFT_ON_CLOCK = "DRAFT_ON_CLOCK",

  WEEK_RESOLVE = "WEEK_RESOLVE",
  SCHEDULE_GEN = "SCHEDULE_GEN",

  OFFSEASON_REVIEW = "OFFSEASON_REVIEW",
  RETIREMENTS = "RETIREMENTS",
  RESTRUCTURES = "RESTRUCTURES",
  OFFSEASON_CUTS = "OFFSEASON_CUTS",
  NEXT_DRAFT_ORDER = "NEXT_DRAFT_ORDER"
}
