export enum GateCode {
  MISSING_MASTER_SEED = "MISSING_MASTER_SEED",
  SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH",
  CHECKPOINT_HASH_INVALID = "CHECKPOINT_HASH_INVALID",

  FRANCHISE_NOT_SELECTED = "FRANCHISE_NOT_SELECTED",
  HC_GM_REQUIRED = "HC_GM_REQUIRED",

  CAP_NONCOMPLIANT = "CAP_NONCOMPLIANT",
  ROSTER_TOO_LARGE = "ROSTER_TOO_LARGE",
  ROSTER_TOO_SMALL = "ROSTER_TOO_SMALL",
  DEPTH_CHART_INCOMPLETE = "DEPTH_CHART_INCOMPLETE",

  DRAFT_ORDER_NOT_FINAL = "DRAFT_ORDER_NOT_FINAL",
  DRAFT_POOL_NOT_LOCKED = "DRAFT_POOL_NOT_LOCKED",
  USER_ON_CLOCK = "USER_ON_CLOCK",

  WEEK_NOT_RESOLVED = "WEEK_NOT_RESOLVED",
  SCHEDULE_MISSING = "SCHEDULE_MISSING",

  OFFSEASON_REVIEW_INCOMPLETE = "OFFSEASON_REVIEW_INCOMPLETE",
  RETIREMENTS_NOT_RESOLVED = "RETIREMENTS_NOT_RESOLVED",
  RESTRUCTURES_NOT_RESOLVED = "RESTRUCTURES_NOT_RESOLVED",
  OFFSEASON_CUTS_INCOMPLETE = "OFFSEASON_CUTS_INCOMPLETE",
  NEXT_DRAFT_ORDER_NOT_FINAL = "NEXT_DRAFT_ORDER_NOT_FINAL"
}
